[variables]
PORT = "8000"

[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = ["python3.11 -m ensurepip", "python3.11 -m pip install -r requirements.txt"]

[phases.start]
cmd = "python3.11 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
