"""Remove clinic_id from instruments

Revision ID: c9a3cc64ff1f
Revises: feb8d08ee170
Create Date: 2025-04-06 14:45:24.433731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9a3cc64ff1f'
down_revision: Union[str, None] = 'feb8d08ee170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('instruments_ibfk_1', 'instruments', type_='foreignkey')
    op.drop_column('instruments', 'clinic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('clinic_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('instruments_ibfk_1', 'instruments', 'clinics', ['clinic_id'], ['id'])
    # ### end Alembic commands ###
