"""Add roles and clinic scoping

Revision ID: feb8d08ee170
Revises: 808d061448e5
Create Date: 2025-04-05 20:27:09.046527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'feb8d08ee170'
down_revision: Union[str, None] = '808d061448e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_index('name', table_name='clinics')
    op.drop_column('clinics', 'clinicLoc')
    op.add_column('instruments', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instruments', 'clinics', ['clinic_id'], ['id'])
    op.alter_column('instruments_and_procedures', 'procedure_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('instruments_and_procedures', 'instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('instruments_and_procedures', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.add_column('packs', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'packs', 'clinics', ['clinic_id'], ['id'])
    op.alter_column('packs_and_instruments', 'pack_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('packs_and_instruments', 'instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('packs_and_instruments', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('packs_and_procedures', 'pack_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('packs_and_procedures', 'procedure_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('procedures', sa.Column('clinic_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_procedures_id'), 'procedures', ['id'], unique=False)
    op.create_index(op.f('ix_procedures_name'), 'procedures', ['name'], unique=True)
    op.create_foreign_key(None, 'procedures', 'clinics', ['clinic_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_index(op.f('ix_procedures_name'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_id'), table_name='procedures')
    op.drop_column('procedures', 'clinic_id')
    op.alter_column('packs_and_procedures', 'procedure_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('packs_and_procedures', 'pack_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('packs_and_instruments', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('packs_and_instruments', 'instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('packs_and_instruments', 'pack_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'packs', type_='foreignkey')
    op.drop_column('packs', 'clinic_id')
    op.alter_column('instruments_and_procedures', 'quantity',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('instruments_and_procedures', 'instrument_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('instruments_and_procedures', 'procedure_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'instruments', type_='foreignkey')
    op.drop_column('instruments', 'clinic_id')
    op.add_column('clinics', sa.Column('clinicLoc', mysql.VARCHAR(length=255), nullable=True))
    op.create_index('name', 'clinics', ['name'], unique=False)
    op.drop_column('clinics', 'location')
    # ### end Alembic commands ###
